# Generated by Django 4.1 on 2023-07-19 17:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Album",
            fields=[
                ("album_id", models.AutoField(primary_key=True, serialize=False)),
                ("album_name", models.CharField(max_length=50)),
            ],
            options={
                "ordering": ["album_name"],
            },
        ),
        migrations.CreateModel(
            name="Comments",
            fields=[
                ("comments_id", models.AutoField(primary_key=True, serialize=False)),
                ("content", models.CharField(default="jjjjjj", max_length=200)),
            ],
            options={
                "ordering": ["content"],
            },
        ),
        migrations.CreateModel(
            name="Photo",
            fields=[
                ("photo_id", models.AutoField(primary_key=True, serialize=False)),
                ("photo_caption", models.CharField(max_length=100)),
                ("photo_description", models.CharField(max_length=200)),
            ],
            options={
                "ordering": ["photo_caption"],
            },
        ),
        migrations.CreateModel(
            name="PhotoDate",
            fields=[
                ("photo_date_id", models.AutoField(primary_key=True, serialize=False)),
                ("photo_date", models.CharField(max_length=10)),
            ],
            options={
                "ordering": ["photo_date"],
            },
        ),
        migrations.CreateModel(
            name="PhotoLocation",
            fields=[
                (
                    "photo_location_id",
                    models.AutoField(primary_key=True, serialize=False),
                ),
                ("photo_location", models.CharField(max_length=10)),
            ],
            options={
                "ordering": ["photo_location"],
            },
        ),
        migrations.CreateModel(
            name="PhotoTag",
            fields=[
                ("photo_tag_id", models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                "ordering": ["photo", "tag"],
            },
        ),
        migrations.CreateModel(
            name="PhotoType",
            fields=[
                ("photo_type_id", models.AutoField(primary_key=True, serialize=False)),
                ("photo_type", models.CharField(max_length=20)),
            ],
            options={
                "ordering": ["photo_type"],
            },
        ),
        migrations.CreateModel(
            name="Tag",
            fields=[
                ("tag_id", models.AutoField(primary_key=True, serialize=False)),
                ("tag_name", models.CharField(max_length=50)),
            ],
            options={
                "ordering": ["tag_name"],
            },
        ),
        migrations.AddConstraint(
            model_name="tag",
            constraint=models.UniqueConstraint(fields=("tag_name",), name="unique_tag"),
        ),
        migrations.AddConstraint(
            model_name="phototype",
            constraint=models.UniqueConstraint(
                fields=("photo_type",), name="unique_phototype"
            ),
        ),
        migrations.AddField(
            model_name="phototag",
            name="photo",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="photoinfo.photo"
            ),
        ),
        migrations.AddField(
            model_name="phototag",
            name="tag",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="photoinfo.tag"
            ),
        ),
        migrations.AddConstraint(
            model_name="photodate",
            constraint=models.UniqueConstraint(
                fields=("photo_date",), name="unique_photodate"
            ),
        ),
        migrations.AddField(
            model_name="photo",
            name="photo_album",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="photoinfo.album"
            ),
        ),
        migrations.AddField(
            model_name="photo",
            name="photo_date",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="photoinfo.photodate"
            ),
        ),
        migrations.AddField(
            model_name="photo",
            name="photo_location",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to="photoinfo.photolocation",
            ),
        ),
        migrations.AddField(
            model_name="photo",
            name="photo_type",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="photoinfo.phototype"
            ),
        ),
        migrations.AddField(
            model_name="comments",
            name="photo",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="photoinfo.photo"
            ),
        ),
        migrations.AddConstraint(
            model_name="album",
            constraint=models.UniqueConstraint(
                fields=("album_name",), name="unique_album"
            ),
        ),
        migrations.AddConstraint(
            model_name="phototag",
            constraint=models.UniqueConstraint(
                fields=("photo", "tag"), name="unique_phototag"
            ),
        ),
        migrations.AddConstraint(
            model_name="photo",
            constraint=models.UniqueConstraint(
                fields=("photo_caption",), name="unique_photo"
            ),
        ),
    ]
