# Generated by Django 4.1 on 2023-07-19 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("photoinfo", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="comments",
            name="content",
            field=models.CharField(max_length=200),
        ),
    ]
